### ISSUE TITLE
ok, so not an issue, buuuut

### ISSUE THREAD

**Issue by Flyingbacen** [snappycreeper/OldDiscordFont#3]
Discord has revoked access to the font files with error code 1020, so essentially, yeah, you can't access them except by here now

> Access denied
Error code 1020
>
> You do not have access to discord.com.
>
> The site owner may have set restrictions that prevent you from accessing the site.

**Comment by snappycreeper** [comment]
Hey, thank you for reaching out, I updated the theme to use the fonts from github!

**Comment by golyalpha** [comment]
Huh, interesting, I have been able to get the fonts up until now, when I started getting a 404 on the assets. Was planning to create a PR with the same changes. 🙃
